pages:
  stage: deploy
  script:
  - mkdir -p /var/www/site/api
  - 'if find . -type f -name "*.php" -exec nice php -l {} \; | grep -v "No syntax errors"; then false; else echo "No syntax errors"; fi'
  - git --work-tree=/var/www/site/api checkout -f
  - sshpass -p $SSHPASS ssh tlo@localhost "cd $PWD; git push --force --mirror git@github.com:TLOxyz/API.git ;"
  only:
  - master